friendly_name=Servidor DLNA de Rodrigo

network_interface=lo,enp0s31f6,wlp5s0

port=8200
user=minidlna
max_connections=50

db_dir=/var/cache/minidlna

log_dir=/var/log/minidlna
log_level=general,artwork,database,inotify,scanner,metadata,http,ssdp,tivo=warn

root_container=.
media_dir=A,/opt/minidlna/Music
media_dir=P,/opt/minidlna/Pictures
media_dir=V,/opt/minidlna/Videos

enable_thumbnail=yes
enable_thumbnail_filmstrip=yes
thumbnail_width=160
thumbnail_quality=8

album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg
force_sort_criteria=+upnp:class,+upnp:originalTrackNumber,+dc:title
merge_media_dirs=no
wide_links=no

strict_dlna=no

serial=15173951
model_number=1
model_name=Servidor DLNA de Rodrigo

enable_subtitles=yes
minissdpdsocket=/var/run/minissdpd.sock
# presentation_url=/

inotify=yes
notify_interval=60

enable_tivo=no
tivo_discovery=bonjour
