#!/usr/bin/env zsh

plugins=( battery colored-man-pages colorize command-not-found common-aliases composer dircycle dirhistory dotenv emoji encode64
git git-extras github gitignore gpg-agent history-substring-search history jsontools lol man nmap node npm per-directory-history
postgres rand-quote redis-cli rsync shrink-path ssh-agent sudo tmux urltools vi-mode vim-interaction web-search zsh-completions
zsh-syntax-highlighting)

fpath+=$HOME/.oh-my-zsh/plugins/zsh-completions/src
source $ZSH/oh-my-zsh.sh

source $HOME/.zshaliases
source $HOME/.zshfunctions

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"

if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

if command -v direnv >/dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

source $HOME/.zshoptions

if command -v fastfetch >/dev/null 2>&1; then
  fastfetch
fi
